# Generated by Django 4.0.5 on 2023-04-13 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='unknown.jpeg', null=True, upload_to='')),
                ('telephone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('house_number', models.IntegerField(default=1)),
                ('city', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=40)),
                ('cap', models.IntegerField(default=11111)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
