# Generated by Django 4.0.5 on 2023-04-14 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=30)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('productor', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0)),
                ('full_price', models.FloatField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('final_price', models.FloatField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('display_size', models.FloatField(default=0)),
                ('display_resolution', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.PositiveIntegerField(default=0)),
                ('disk_size', models.FloatField(default=0)),
                ('disk_type', models.CharField(max_length=20)),
                ('operating_system', models.CharField(max_length=100)),
                ('graphic_card', models.CharField(max_length=50)),
                ('battery_autonomy', models.FloatField(default=0)),
                ('additional_function', models.CharField(max_length=1000)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('display_size', models.FloatField(default=0)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.PositiveIntegerField(default=0)),
                ('disk_size', models.FloatField(default=0)),
                ('operating_system', models.CharField(max_length=100)),
                ('battery_autonomy', models.FloatField(default=0)),
                ('camera', models.IntegerField(default=0)),
                ('additional_function', models.CharField(max_length=1000)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutation', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='recensioni',
            field=models.ManyToManyField(to='products.recensione'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
