# Generated by Django 4.0.5 on 2023-01-26 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('1', 'computer'), ('2', 'smartphone')], default=1, max_length=20)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('productor', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=10)),
                ('price', models.FloatField(default=10)),
                ('available', models.BooleanField(default=False)),
                ('num_visits', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_size', models.FloatField(default=13.5)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.PositiveIntegerField(default=0)),
                ('disk_size', models.FloatField(max_length=20)),
                ('operating_system', models.CharField(max_length=100)),
                ('battery_autonomy', models.FloatField(max_length=50)),
                ('camera', models.IntegerField(default=0)),
                ('additional_function', models.CharField(max_length=1000)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutation', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ordine', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_size', models.FloatField(default=13.5)),
                ('display_resolution', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=20)),
                ('disk_size', models.FloatField(max_length=20)),
                ('disk_type', models.CharField(max_length=20)),
                ('operating_system', models.CharField(max_length=100)),
                ('graphic_card', models.CharField(max_length=50)),
                ('battery_autonomy', models.FloatField(max_length=50)),
                ('additional_function', models.CharField(max_length=1000)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
