# Generated by Django 4.0.5 on 2023-01-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
