# Generated by Django 4.0.5 on 2023-01-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_ordine_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='id_ordine',
            field=models.CharField(max_length=20),
        ),
    ]
