# Generated by Django 4.0.5 on 2023-01-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_ordine_id_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='id_ordine',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
