# Generated by Django 4.0.5 on 2023-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_ordine_client_alter_ordine_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='computer',
            name='battery_autonomy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='computer',
            name='disk_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='computer',
            name='display_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_autonomy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='disk_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='display_size',
            field=models.FloatField(default=0),
        ),
    ]
