# Generated by Django 4.0.5 on 2023-04-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_num_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
